import pdb

from models.lesson import Lesson
from models.member import Member
from models.booking import Booking

import repositories.lesson_repository as lesson_repository
import repositories.member_repository as member_repository
import repositories.booking_repository as booking_repository

booking_repository.delete_all()
lesson_repository.delete_all()
member_repository.delete_all()

lesson1 = Lesson('Sun Salutations', 10, 'Intermediate', 'Monday', "08:00", 60)
lesson_repository.save(lesson1)
lesson2 = Lesson('Sun Salutations', 10, 'Intermediate', 'Wednesday', "08:00", 60)
lesson_repository.save(lesson2)
lesson3 = Lesson('Sun Salutations', 10, 'Intermediate', 'Friday', "08:00", 60)
lesson_repository.save(lesson3)

lesson4 = Lesson('Yoga for Flexibility', 20, 'Beginner', 'Tuesday', "17:00", 45)
lesson_repository.save(lesson4)
lesson5 = Lesson('Yoga for Flexibility', 20, 'Beginner', 'Thursday', "17:00", 45)
lesson_repository.save(lesson5)

lesson6 = Lesson('Yoga for Geriatrics', 5, 'Beginner', 'Wednesday', "11:00", 90)
lesson_repository.save(lesson6)
lesson7 = Lesson('Yoga for Geriatrics', 5, 'Beginner', 'Saturday', "11:00", 90)
lesson_repository.save(lesson7)

lesson8 = Lesson('Prenatal Yoga', 5, 'Beginner', 'Tuesday', "10:00", 60)
lesson_repository.save(lesson8)
lesson9 = Lesson('Prenatal Yoga', 5, 'Beginner', 'Friday', "10:00", 60)
lesson_repository.save(lesson9)

lesson10 = Lesson('Airbending', 10, 'Advanced', 'Monday', "18:00", 120)
lesson_repository.save(lesson10)
lesson11 = Lesson('Ninja Skills', 10, 'Advanced', 'Thursday', "18:00", 120)
lesson_repository.save(lesson11)
lesson12 = Lesson('How to kill your Spouse', 10, 'Advanced', 'Saturday', "14:00", 60)
lesson_repository.save(lesson12)
lesson13 = Lesson('Kilted Yoga', 10, 'Advanced', 'Saturday', "12:00", 90)
lesson_repository.save(lesson13)

member1 = Member('Ginny Miller', 'Deluxe')
member_repository.save(member1)
booking1 = Booking(member1, lesson1)
booking_repository.save(booking1)
booking2 = Booking(member1, lesson2)
booking_repository.save(booking2)
booking3 = Booking(member1, lesson3)
booking_repository.save(booking3)
booking4 = Booking(member1, lesson11)
booking_repository.save(booking4)

member2 = Member('Maxine Baker', 'Deluxe')
member_repository.save(member2)
booking5 = Booking(member2, lesson4)
booking_repository.save(booking5)
booking6 = Booking(member2, lesson5)
booking_repository.save(booking6)
booking7 = Booking(member2, lesson11)
booking_repository.save(booking7)

member3 = Member('Abby Mang', 'Standard')
member_repository.save(member3)
booking8 = Booking(member3, lesson4)
booking_repository.save(booking8)
booking9 = Booking(member3, lesson5)
booking_repository.save(booking9)
booking10 = Booking(member3, lesson10)
booking_repository.save(booking10)

member4 = Member('Nadine Mang', 'Deluxe')
member_repository.save(member4)
booking11 = Booking(member4, lesson1)
booking_repository.save(booking11)
booking12 = Booking(member4, lesson2)
booking_repository.save(booking12)
booking13 = Booking(member4, lesson3)
booking_repository.save(booking13)
booking14 = Booking(member4, lesson10)
booking_repository.save(booking14)

member5 = Member('Georgia Miller', 'Deluxe')
member_repository.save(member5)
booking15 = Booking(member5, lesson1)
booking_repository.save(booking15)
booking16 = Booking(member5, lesson2)
booking_repository.save(booking16)
booking17 = Booking(member5, lesson3)
booking_repository.save(booking17)
booking18 = Booking(member5, lesson12)
booking_repository.save(booking18)

member6 = Member('Hunter Chen', 'Standard')
member_repository.save(member6)
booking19 = Booking(member6, lesson10)
booking_repository.save(booking19)

member7 = Member('Marcus Baker', 'Deluxe')
member_repository.save(member7)
booking20 = Booking(member7, lesson11)
booking_repository.save(booking20)

member8 = Member('Ellen Baker', 'Deluxe')
member_repository.save(member8)
booking21 = Booking(member8, lesson6)
booking_repository.save(booking21)
booking22 = Booking(member8, lesson7)
booking_repository.save(booking22)

member9 = Member('Paul Randolph', 'Standard')
member_repository.save(member9)
booking23 = Booking(member9, lesson6)
booking_repository.save(booking23)
booking24 = Booking(member9, lesson7)
booking_repository.save(booking24)
booking38 = Booking(member9, lesson13)
booking_repository.save(booking38)

member10 = Member('Zion Miller', 'Deluxe')
member_repository.save(member10)
booking25 = Booking(member10, lesson1)
booking_repository.save(booking25)
booking26 = Booking(member10, lesson2)
booking_repository.save(booking26)
booking27 = Booking(member10, lesson3)
booking_repository.save(booking27)
booking28 = Booking(member10, lesson10)
booking_repository.save(booking28)
booking29 = Booking(member10, lesson11)
booking_repository.save(booking29)
booking39 = Booking(member10, lesson13)
booking_repository.save(booking39)

member11 = Member('Sophie Sanchez', 'Standard')
member_repository.save(member11)
booking30 = Booking(member11, lesson4)
booking_repository.save(booking30)
booking31 = Booking(member11, lesson5)
booking_repository.save(booking31)

member12 = Member('Cynthia Fuller', 'Deluxe')
member_repository.save(member12)
booking32 = Booking(member12, lesson6)
booking_repository.save(booking32)
booking33 = Booking(member12, lesson7)
booking_repository.save(booking33)

member13 = Member('Gabriel Cordova', 'Deluxe')
member_repository.save(member13)
booking34 = Booking(member13, lesson12)
booking_repository.save(booking34)
booking40 = Booking(member13, lesson13)
booking_repository.save(booking40)

member14 = Member('Joe Danes', 'Deluxe')
member_repository.save(member14)
booking35 = Booking(member14, lesson1)
booking_repository.save(booking35)
booking36 = Booking(member14, lesson2)
booking_repository.save(booking36)
booking37 = Booking(member14, lesson3)
booking_repository.save(booking37)
booking41 = Booking(member14, lesson13)
booking_repository.save(booking41)
booking43 = Booking(member14, lesson6)
booking_repository.save(booking43)

member15 = Member('Nick Bierne', 'Standard')
member_repository.save(member15)
booking42 = Booking(member15, lesson13)
booking_repository.save(booking42)
booking44 = Booking(member15, lesson6)
booking_repository.save(booking44)



